services:
  - type: web
    name: image-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PERCHANCE_WORKER_URL
        sync: false

  - type: web
    name: perchance-worker
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./render_worker/Dockerfile
    dockerContext: ./render_worker
    envVars:
      - key: IMGUR_CLIENT_ID
        sync: false
